CREATE SEQUENCE user_sequence START 1;

CREATE TABLE users(
  ID 				    INTEGER PRIMARY KEY DEFAULT nextval('user_sequence'),
  PROVIDER 			    VARCHAR(50) NOT NULL,
  USER_ID 			    VARCHAR(50) NOT NULL,
  USER_NAME 			VARCHAR(50) NOT NULL,
  EMAIL 				VARCHAR(50) NOT NULL,
  DISPLAY_NAME 		    VARCHAR(50),
  PROFILE_PICTURE_URL   VARCHAR(500),
  TOKEN 				VARCHAR(1000),
  EXPIRE_TIME 		    TIMESTAMP,
  CREATED_AT 			TIMESTAMP,
  LAST_LOGIN_AT 		TIMESTAMP
);